### ISSUE TITLE
Unable to create a TabPFN account

### ISSUE THREAD

**Issue by zongyaowang-bjtu** [automl/tabpfn-client#37]
This code handles tabular data classification very efficiently and is great code. However, when I run the code, I find that I cannot create or log in to TabPFN accounts, I would be grateful if you know how to solve this problem.
![微信截图_20240919145102](https://github.com/user-attachments/assets/bf992129-d92d-4f75-a7b8-c52611431c4e)

**Comment by zongyaowang-bjtu** [comment]
@liam-sbhoo
Thank you for your reply. As the picture I attached shows, after running the code to the input email, the entire program does not have any feedback. No error tracking is displayed. My main problem is still not being able to create or log in to TabPFN.

**Comment by zongyaowang-bjtu** [comment]
@liam-sbhoo
Thanks for your reply. I would like to know whether it is the problem of the enter button, and what should I do after entering the email address? I press the enter button directly, but there is no response after I press the button.

**Comment by liam-sbhoo** [comment]
Ideally, you should be prompt for password (see below).
![image](https://github.com/user-attachments/assets/06fdd3eb-4758-45e6-8ab4-3c4e3b7068ec)

Could you try using the Colab Notebook (mentioned in the README) we provided?

**Comment by zongyaowang-bjtu** [comment]
Thanks for your reply and help, I have solved the problem :)
