### ISSUE TITLE
RuntimeError: Client version too old. Please update to version 0.0.25 or newer.

### ISSUE THREAD

**Issue by ashysheya** [automl/tabpfn-client#55]
Hi, many thanks for realising the TabPFN-client! 

I'm trying to use it now for regression and classification, both from a local machine and from the colab you shared. However, I am currently getting this error: `RuntimeError: Client version too old. Please update to version 0.0.25 or newer.` 

I was trying to update the client version to 0.0.25, but pip doesn't seem to be able to find it. Do you have any idea how I can fix this issue? 

Best, 
Aliaksandra

**Comment by noahho** [comment]
Dear Aliaksandra,

thanks for letting us know!

Could you retry running:
`pip install tabpfn-client==0.0.25`

Best

**Comment by jfb54** [comment]
This worked for me.

**Comment by yufeit** [comment]
Good Day!

I'm trying use it for table too, but I got a similar problem like yours: RuntimeError: Client version too old. Please update to version 0.1.0 or newer.
But it seems like the newest verison would be 0.0.25, and I would like to know if you have any idea about how to solve this problem?

sorry for my broken English, many many thank!

Best,
Akina

**Comment by noahho** [comment]
No worries! Try running "pip install tabpfn-client --upgrade"

**Comment by yufeit** [comment]
It says that "Requirement already satisfied",  maybe the newest verison would be 0.0.25.
Still thank you very much!  Maybe there are some problems in my code that I didn't find.

**Comment by yufeit** [comment]
Updates: the problem have be solved!
It happens that I haven't set my python project environment correct, it needs a python 3.10 in conda.
