### ISSUE TITLE
Crash when running tutorial or script with sample code

### ISSUE THREAD

**Issue by jfb54** [automl/tabpfn-client#56]
TypeError                                 Traceback (most recent call last)
[<ipython-input-2-06d555b36174>](https://localhost:8080/#) in <cell line: 5>()
      4 token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMjlkYTg0NDYtMTA5Zi00MGNjLWIyNTgtZDYwMDJkNTFlYTkyIiwiZXhwIjoxNzY2MjQ5OTc0fQ.rLzVJCkp4odVjDmODx0LLAaPf56SDzTlhiAMgu4z6ds'
      5 if token:
----> 6   service_client = config.ServiceClient()
      7   config.g_tabpfn_config.user_auth_handler = config.UserAuthenticationClient(service_client=service_client)
      8   user_auth = config.g_tabpfn_config.user_auth_handler.set_token(token)

[/usr/local/lib/python3.10/dist-packages/tabpfn_client/tabpfn_common_utils/utils.py](https://localhost:8080/#) in __new__(cls)
     41 class Singleton:
     42     def __new__(cls):
---> 43         raise TypeError("Cannot instantiate this class. This is a singleton.")
     44 
     45 

TypeError: Cannot instantiate this class. This is a singleton.

**Comment by noahho** [comment]
Ohh thanks for catching that! We just updated the getter and setter to something more convenient:

```
Save Your Token
import tabpfn_client
token = tabpfn_client.get_access_token()
and login (on another machine) using your access token, skipping the interactive flow, use:

tabpfn_client.set_access_token(token)

```

Updated in the colab as well.
