### ISSUE TITLE
Service is failing with error: sqlalchemy.exc.TimeoutError: QueuePool limit of size 20 overflow 20 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)

### ISSUE THREAD

**Issue by jfb54** [automl/tabpfn-client#57]
sqlalchemy.exc.TimeoutError: QueuePool limit of size 20 overflow 20 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)

**Comment by noahho** [comment]
Thanks for raising this - we have fixed this issue now. Could you recheck if everything works for you now? Thanks!

**Comment by jfb54** [comment]
Yes, works fine now. Thanks for the fix.
