### ISSUE TITLE
Intermittent failure: RuntimeError: InternalServerError: TypeError: 'NoneType' object is not subscriptable 

### ISSUE THREAD

**Issue by jfb54** [automl/tabpfn-client#58]
When I run a simple regression or classification test, I get the error:
RuntimeError: InternalServerError: TypeError: 'NoneType' object is not subscriptable

This happens roughly half the time. If I run the same task again, it often completes just fine or sometimes fails with the above error.

Happy to help you debug this if need be.

**Comment by noahho** [comment]
We'll be onto it. If you could help show an example, that would be great!

**Comment by jfb54** [comment]
Here is some code that will reproduce the issue. I also attached a zip file with the data in it. You will need to unzip the file and put it beside this script. Good luck!

from tabpfn_client import set_access_token, TabPFNClassifier, TabPFNRegressor
from sklearn.metrics import mean_absolute_error, accuracy_score
import numpy as np
import pickle

token = 'your token here'

def main():
    set_access_token(token)

    with open('data.pkl', 'rb') as f:
        data = pickle.load(f)

    # regress column 11
    regressor = TabPFNRegressor()
    regressor.fit(
        np.ascontiguousarray(data['x_train'][:, 0 : 11]),
        np.ascontiguousarray(data['x_train'][:, 11])
    )
    predictions1 = regressor.predict_full(np.ascontiguousarray(data['x_test'][:, 0 : 11]))
    mae_1 = mean_absolute_error(np.ascontiguousarray(data['x_test'][:, 11]), predictions1['median'])
    print("MAE = {}".format(mae_1))

    # need to put the regression predictions into x_test
    data['x_test'][:, 11] = predictions1['median']
    data['xtest'] = np.ascontiguousarray(data['x_test'])

    # classify the y column
    classifier = TabPFNClassifier()
    classifier.fit(data['x_train'], data['y_train'])
    probabilities = classifier.predict_proba(data['x_test'])
    predictions_2 = np.argmax(probabilities, axis=-1)
    accuracy_1 = accuracy_score(data['y_test'], predictions_2 + 3)
    print("Accuracy = {}".format(accuracy_1))


if __name__ == '__main__':
    main()
[data.zip](https://github.com/user-attachments/files/18276664/data.zip)

**Comment by noahho** [comment]
Thanks a lot, we'll keep you up to date!

**Comment by LeoGrin** [comment]
@jfb54 thanks a lot for reporting the error and for the detailed code to reproduce it! It should be fixed now :)
